# STEP 1
- import & Clean DATA
- learning about the data

In [1]:
import sys
import pandas as pd
import numpy as np
print( f"Python {sys.version}\nPandas {pd.__version__}\nNumPy {np.__version__}\n" )

Python 3.10.4 (main, Jan 25 2023, 00:13:50) [GCC 9.4.0]
Pandas 1.5.3
NumPy 1.24.1

In [2]:
df_w = pd.read_csv('https://raw.githubusercontent.com/HikariJadeEmpire/TH_WLRD_Happiness_Project/main/DataForTable2')  
df_w_overall = pd.read_csv('https://raw.githubusercontent.com/HikariJadeEmpire/TH_WLRD_Happiness_Project/main/Appendix_2_Data_for_Figure_2')

df_w.info(); print('\n') # we will use this to be the main file
#df_w_overall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Country name                       2089 non-null   object
 1   year                               2089 non-null   int64
 2   Life Ladder                        2089 non-null   float64
 3   Log GDP per capita                 2062 non-null   float64
 4   Social support                     2076 non-null   float64
 5   Healthy life expectancy at birth   2031 non-null   float64
 6   Freedom to make life choices       2057 non-null   float64
 7   Generosity                         2009 non-null   float64
 8   Perceptions of corruption          1976 non-null   float64
 9   Positive affect                    2065 non-null   float64
 10  Negative affect                    2073 non-null   float64
 11  Confidence in national government  1873 non-null   float64
dtypes: float64(10), int64(1), object(1)
memory usage: 196.0+ KB

In [3]:
# Clean Column name to avoid error (eg.remove 'space')

df = df_w.loc[:]
df.rename(columns={'Country name':'country_name',
'Life Ladder':'life_lad','Log GDP per capita':'gdp_per_cap',
'Social support':'social_sup','Healthy life expectancy at birth':'health',
'Freedom to make life choices':'life_choice','Generosity':'generosity',
'Perceptions of corruption':'corruption','Positive affect':'pos_aff','Negative affect':'neg_aff',
'Confidence in national government':'conf_in_gov'},inplace=True)

# get results
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country_name  2089 non-null   object
 1   year          2089 non-null   int64
 2   life_lad      2089 non-null   float64
 3   gdp_per_cap   2062 non-null   float64
 4   social_sup    2076 non-null   float64
 5   health        2031 non-null   float64
 6   life_choice   2057 non-null   float64
 7   generosity    2009 non-null   float64
 8   corruption    1976 non-null   float64
 9   pos_aff       2065 non-null   float64
 10  neg_aff       2073 non-null   float64
 11  conf_in_gov   1873 non-null   float64
dtypes: float64(10), int64(1), object(1)
memory usage: 196.0+ KB

In [4]:
# Replace NaN by median respect to country

for i,name in enumerate(list(df)):
    if i > 2 :
        df[name].fillna(df.groupby(['country_name'])[name].transform('median'),inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country_name  2089 non-null   object
 1   year          2089 non-null   int64
 2   life_lad      2089 non-null   float64
 3   gdp_per_cap   2073 non-null   float64
 4   social_sup    2088 non-null   float64
 5   health        2051 non-null   float64
 6   life_choice   2089 non-null   float64
 7   generosity    2073 non-null   float64
 8   corruption    2060 non-null   float64
 9   pos_aff       2087 non-null   float64
 10  neg_aff       2088 non-null   float64
 11  conf_in_gov   1992 non-null   float64
dtypes: float64(10), int64(1), object(1)
memory usage: 196.0+ KB

Look like some of them are still NaN.<br>
We've got to see what happened.

In [5]:
see=df.loc[ df['gdp_per_cap'].isna() | df['social_sup'].isna() | df['health'].isna() | df['generosity'].isna() 
           | df['corruption'].isna() | df['conf_in_gov'].isna() | df['neg_aff'].isna() , : ].groupby(by=['country_name'])

print(f"\n {'-'*4} List of countries that have NaN {'-'*4} \n")
for i in (see.groups) :
    print(i)

see1 = df.loc[df['country_name'].isin(['China']) ,:].reset_index(drop=True)
see2 = df.loc[df['country_name'].isin(['Hong Kong S.A.R. of China']) ,:].reset_index(drop=True)

display(see1)
display(see2)

 ---- List of countries that have NaN ----

Algeria
Bahrain
China
Cuba
Hong Kong S.A.R. of China
Kosovo
Libya
Maldives
North Cyprus
Oman
Saudi Arabia
Somaliland region
South Sudan
Sudan
Syria
Turkmenistan
United Arab Emirates

,country_name,year,life_lad,gdp_per_cap,social_sup,health,life_choice,generosity,corruption,pos_aff,neg_aff,conf_in_gov
0,China,2006,4.560495,8.696139,0.747011,65.660004,0.853072,-0.173937,NaN,0.657659,0.169580,NaN
1,China,2007,4.862862,8.823968,0.810852,65.919998,0.853072,-0.176961,NaN,0.663977,0.158614,NaN
2,China,2008,4.846295,8.910974,0.748287,66.180000,0.853072,-0.093270,NaN,0.705133,0.146963,NaN
3,China,2009,4.454361,8.995829,0.798034,66.440002,0.771143,-0.161358,NaN,0.669666,0.161650,NaN
4,China,2010,4.652737,9.092073,0.767753,66.699997,0.804794,-0.134285,NaN,0.658101,0.158100,NaN
5,China,2011,5.037208,9.177827,0.787171,66.959999,0.824162,-0.187382,NaN,0.710055,0.133503,NaN
6,China,2012,5.094917,9.246742,0.787818,67.220001,0.808255,-0.185606,NaN,0.689160,0.158703,NaN
7,China,2013,5.241090,9.314875,0.777896,67.480003,0.804724,-0.158647,NaN,0.717136,0.142211,NaN
8,China,2014,5.195619,9.380201,0.820366,67.739998,0.853072,-0.217615,NaN,0.709763,0.111518,NaN
9,China,2015,5.303878,9.442431,0.793734,68.000000,0.853072,-0.245284,NaN,0.666827,0.171315,NaN
10,China,2016,5.324956,9.502946,0.741703,68.125000,0.853072,-0.228405,NaN,0.683256,0.145625,NaN
11,China,2017,5.099061,9.564058,0.772033,68.250000,0.877618,-0.175740,NaN,0.681665,0.214005,NaN
12,China,2018,5.131434,9.624699,0.787605,68.375000,0.895378,-0.159466,NaN,0.721579,0.189640,NaN
13,China,2019,5.144120,9.678946,0.821936,68.500000,0.927356,-0.173937,NaN,0.760267,0.146512,NaN
14,China,2020,5.771065,9.699890,0.808334,68.625000,0.891123,-0.104621,NaN,0.662961,0.244918,NaN
15,China,2021,5.862864,9.776109,0.856007,68.750000,0.874756,0.023953,NaN,0.697810,0.239618,NaN

,country_name,year,life_lad,gdp_per_cap,social_sup,health,life_choice,generosity,corruption,pos_aff,neg_aff,conf_in_gov
0,Hong Kong S.A.R. of China,2006,5.511187,10.746424,0.812178,NaN,0.909820,0.153046,0.355985,0.591140,0.235955,0.663938
1,Hong Kong S.A.R. of China,2008,5.137262,10.815546,0.840222,NaN,0.922211,0.293682,0.273945,0.575073,0.236634,0.677437
2,Hong Kong S.A.R. of China,2009,5.397056,10.788493,0.834716,NaN,0.918026,0.305077,0.272125,0.606459,0.210104,0.619142
3,Hong Kong S.A.R. of China,2010,5.642835,10.846634,0.857314,NaN,0.890418,0.329340,0.255775,0.600561,0.183106,0.634737
4,Hong Kong S.A.R. of China,2011,5.474011,10.886932,0.846060,NaN,0.894330,0.231902,0.244887,0.582491,0.195712,0.584562
5,Hong Kong S.A.R. of China,2012,5.483765,10.892753,0.826426,NaN,0.879752,0.219744,0.379783,0.580223,0.183349,0.497906
6,Hong Kong S.A.R. of China,2014,5.458051,10.939503,0.833558,NaN,0.843082,0.221097,0.422960,0.602495,0.242868,0.457823
7,Hong Kong S.A.R. of China,2016,5.498421,10.969857,0.832078,NaN,0.799743,0.097504,0.402813,0.568555,0.213115,0.449610
8,Hong Kong S.A.R. of China,2017,5.362475,10.999584,0.831066,NaN,0.830657,0.137305,0.415810,0.535812,0.200593,0.545041
9,Hong Kong S.A.R. of China,2019,5.659317,10.995179,0.855826,NaN,0.726852,0.064956,0.431974,0.519312,0.357607,0.332540
10,Hong Kong S.A.R. of China,2020,5.295341,10.935853,0.812943,NaN,0.705452,-0.072825,0.380351,0.521671,0.210314,0.442211
11,Hong Kong S.A.R. of China,2021,5.321551,10.892753,0.821089,NaN,0.668631,0.219744,0.389589,0.534148,0.223565,0.495274

Here is the list of countries that still have NaN.<br> 
We will consider dropping a country that is not in our interest and keeping the interesting one.<br>
Else, we just have to keep them.

Now we decided to keep them <br>
It's time to learn the features of DATA<br>
# STEP 2
- sort value by life ladder, from the best to the worst.
- Learn from the best, define what the most happiness country looks like.

In [15]:
# sort by the best mean of life_lad

df = df.groupby(['country_name']).apply(lambda x : x[['life_lad','gdp_per_cap','social_sup',
    'health','life_choice','generosity','corruption','pos_aff',
    'neg_aff','conf_in_gov']].mean()).sort_values(by=['life_lad'],ascending=False)

display(df)

,life_lad,gdp_per_cap,social_sup,health,life_choice,generosity,corruption,pos_aff,neg_aff,conf_in_gov
country_name,,,,,,,,,,
Denmark,7.681457,10.885137,0.956441,70.031562,0.944400,0.165070,0.198672,0.783656,0.197597,0.578037
Finland,7.611299,10.753935,0.950494,70.325358,0.941380,-0.001996,0.244848,0.738809,0.185581,0.596645
Switzerland,7.528177,11.127461,0.942772,71.978181,0.923328,0.094757,0.304179,0.756787,0.189489,0.770718
Norway,7.498840,11.059574,0.950138,70.931818,0.952737,0.135409,0.336738,0.786417,0.201050,0.675312
Iceland,7.459697,10.878041,0.977832,71.816666,0.930586,0.255945,0.696809,0.810800,0.162326,0.428385
...,...,...,...,...,...,...,...,...,...,...
Togo,3.603208,7.538181,0.470834,54.076000,0.622879,-0.041133,0.799416,0.564185,0.419719,0.424578
Burundi,3.548124,6.722510,0.417652,52.008000,0.451014,-0.035402,0.732270,0.570199,0.244124,0.736995
Central African Republic,3.514954,6.960999,0.402559,43.374000,0.680430,0.027961,0.842129,0.539942,0.391497,0.711735
Afghanistan,3.505506,7.586585,0.504086,52.353846,0.508496,0.077007,0.851207,0.450821,0.348225,0.382015
South Sudan,3.401875,NaN,0.554719,53.101250,0.493705,NaN,0.749433,0.572469,0.486184,0.468385