# STEP 1
- import & Clean DATA
- learning about the data

In [1]:
import sys
import pandas as pd
import numpy as np
print( f"Python {sys.version}\nPandas {pd.__version__}\nNumPy {np.__version__}\n" )

Python 3.10.4 (main, Jan 25 2023, 00:13:50) [GCC 9.4.0]
Pandas 1.5.3
NumPy 1.24.1

In [27]:
df_w = pd.read_csv('https://raw.githubusercontent.com/HikariJadeEmpire/TH_WLRD_Happiness_Project/main/DataForTable2')  
df_w_overall = pd.read_csv('https://raw.githubusercontent.com/HikariJadeEmpire/TH_WLRD_Happiness_Project/main/Appendix_2_Data_for_Figure_2')

df_w.info(); print('\n') # we will use this to be the main file
#df_w_overall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Country name                       2089 non-null   object
 1   year                               2089 non-null   int64
 2   Life Ladder                        2089 non-null   float64
 3   Log GDP per capita                 2062 non-null   float64
 4   Social support                     2076 non-null   float64
 5   Healthy life expectancy at birth   2031 non-null   float64
 6   Freedom to make life choices       2057 non-null   float64
 7   Generosity                         2009 non-null   float64
 8   Perceptions of corruption          1976 non-null   float64
 9   Positive affect                    2065 non-null   float64
 10  Negative affect                    2073 non-null   float64
 11  Confidence in national government  1873 non-null   float64
dtypes: float64(10), int64(1), object(1)
memory usage: 196.0+ KB

In [51]:
# Clean Column name to avoid error (eg.remove 'space')

df = df_w.loc[:]
df.rename(columns={'Country name':'country_name','Life \
    Ladder':'life_lad','Log GDP per capita':'gdp_per_cap','Social \
    support':'social_sup','Healthy life expectancy at birth':'health','\
    Freedom to make life choices':'life_choice','Generosity':'generosity\
    ','Perceptions of corruption':'corruption','Positive affect':'pos_aff\
    ','Negative affect':'neg_aff','Confidence in national government':'conf_in_gov'},inplace=True)

# get results
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country_name                  2089 non-null   object
 1   year                          2089 non-null   int64
 2   Life Ladder                   2089 non-null   float64
 3   gdp_per_cap                   2062 non-null   float64
 4   Social support                2076 non-null   float64
 5   health                        2031 non-null   float64
 6   Freedom to make life choices  2057 non-null   float64
 7   generosity                    2009 non-null   float64
 8   corruption                    1976 non-null   float64
 9   pos_aff                       2065 non-null   float64
 10  neg_aff                       2073 non-null   float64
 11  conf_in_gov                   1873 non-null   float64
dtypes: float64(10), int64(1), object(1)
memory usage: 196.0+ KB

In [61]:
# Replace NaN by median respect to country

for i,name in enumerate(list(df)):
    if i > 2 :
        df[name].fillna(df.groupby(['country_name'])[name].transform('median'),inplace=True)

display(df.loc[ df['gdp_per_cap'].isna() , : ])
df.info()

,country_name,year,Life Ladder,gdp_per_cap,Social support,health,Freedom to make life choices,generosity,corruption,pos_aff,neg_aff,conf_in_gov
449,Cuba,2006,5.417869,NaN,0.969595,68.000000,0.281458,NaN,NaN,0.596187,0.276602,0.513176
1373,North Cyprus,2012,5.463305,NaN,0.871150,NaN,0.692568,NaN,0.854730,0.548641,0.405435,0.414000
1374,North Cyprus,2013,5.566803,NaN,0.869274,NaN,0.775383,NaN,0.715356,0.506441,0.442972,0.401788
1375,North Cyprus,2014,5.785979,NaN,0.801802,NaN,0.829677,NaN,0.692221,0.570316,0.311336,0.412390
1376,North Cyprus,2015,5.842550,NaN,0.791383,NaN,0.785353,NaN,0.659180,0.566849,0.318930,0.439621
1377,North Cyprus,2016,5.827128,NaN,0.807690,NaN,0.796234,NaN,0.670191,0.531509,0.346465,0.440595
1378,North Cyprus,2018,5.608056,NaN,0.837392,NaN,0.797066,NaN,0.613837,0.398250,0.261868,0.378324
1379,North Cyprus,2019,5.466615,NaN,0.803295,NaN,0.792735,NaN,0.640059,0.404271,0.296411,0.370310
1678,Somaliland region,2009,4.991400,NaN,0.879567,NaN,0.746304,NaN,0.513372,0.707874,0.112012,0.538495
1679,Somaliland region,2010,4.657363,NaN,0.829005,NaN,0.820182,NaN,0.471094,0.631947,0.083426,0.587192
1680,Somaliland region,2011,4.930572,NaN,0.787962,NaN,0.858104,NaN,0.357341,0.690514,0.122244,0.760764
1681,Somaliland region,2012,5.057314,NaN,0.786291,NaN,0.758219,NaN,0.333832,0.686732,0.152428,0.651242
1714,South Sudan,2014,3.831992,NaN,0.545118,52.880001,0.567259,NaN,0.741541,0.578410,0.428320,0.446467
1715,South Sudan,2015,4.070771,NaN,0.584781,53.000000,0.511631,NaN,0.709606,0.552726,0.449795,0.509234
1716,South Sudan,2016,2.888112,NaN,0.532152,53.174999,0.439919,NaN,0.785318,0.593741,0.549257,0.456288
1717,South Sudan,2017,2.816622,NaN,0.556823,53.349998,0.456011,NaN,0.761270,0.564999,0.517364,0.461551

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country_name                  2089 non-null   object
 1   year                          2089 non-null   int64
 2   Life Ladder                   2089 non-null   float64
 3   gdp_per_cap                   2073 non-null   float64
 4   Social support                2088 non-null   float64
 5   health                        2051 non-null   float64
 6   Freedom to make life choices  2089 non-null   float64
 7   generosity                    2073 non-null   float64
 8   corruption                    2060 non-null   float64
 9   pos_aff                       2087 non-null   float64
 10  neg_aff                       2088 non-null   float64
 11  conf_in_gov                   1992 non-null   float64
dtypes: float64(10), int64(1), object(1)
memory usage: 196.0+ KB

In [67]:
c_list = ['Cuba','North Cyprus','Somaliland region','South Sudan']

see=df.loc[df['country_name'].isin(c_list),:]; display(see)

,country_name,year,Life Ladder,gdp_per_cap,Social support,health,Freedom to make life choices,generosity,corruption,pos_aff,neg_aff,conf_in_gov
449,Cuba,2006,5.417869,NaN,0.969595,68.000000,0.281458,NaN,NaN,0.596187,0.276602,0.513176
1373,North Cyprus,2012,5.463305,NaN,0.871150,NaN,0.692568,NaN,0.854730,0.548641,0.405435,0.414000
1374,North Cyprus,2013,5.566803,NaN,0.869274,NaN,0.775383,NaN,0.715356,0.506441,0.442972,0.401788
1375,North Cyprus,2014,5.785979,NaN,0.801802,NaN,0.829677,NaN,0.692221,0.570316,0.311336,0.412390
1376,North Cyprus,2015,5.842550,NaN,0.791383,NaN,0.785353,NaN,0.659180,0.566849,0.318930,0.439621
1377,North Cyprus,2016,5.827128,NaN,0.807690,NaN,0.796234,NaN,0.670191,0.531509,0.346465,0.440595
1378,North Cyprus,2018,5.608056,NaN,0.837392,NaN,0.797066,NaN,0.613837,0.398250,0.261868,0.378324
1379,North Cyprus,2019,5.466615,NaN,0.803295,NaN,0.792735,NaN,0.640059,0.404271,0.296411,0.370310
1678,Somaliland region,2009,4.991400,NaN,0.879567,NaN,0.746304,NaN,0.513372,0.707874,0.112012,0.538495
1679,Somaliland region,2010,4.657363,NaN,0.829005,NaN,0.820182,NaN,0.471094,0.631947,0.083426,0.587192
1680,Somaliland region,2011,4.930572,NaN,0.787962,NaN,0.858104,NaN,0.357341,0.690514,0.122244,0.760764
1681,Somaliland region,2012,5.057314,NaN,0.786291,NaN,0.758219,NaN,0.333832,0.686732,0.152428,0.651242
1714,South Sudan,2014,3.831992,NaN,0.545118,52.880001,0.567259,NaN,0.741541,0.578410,0.428320,0.446467
1715,South Sudan,2015,4.070771,NaN,0.584781,53.000000,0.511631,NaN,0.709606,0.552726,0.449795,0.509234
1716,South Sudan,2016,2.888112,NaN,0.532152,53.174999,0.439919,NaN,0.785318,0.593741,0.549257,0.456288
1717,South Sudan,2017,2.816622,NaN,0.556823,53.349998,0.456011,NaN,0.761270,0.564999,0.517364,0.461551